working_dir: "/workspace/verl_with_logging"
excludes: ["/.git/"]
env_vars:
  TORCH_NCCL_AVOID_RECORD_STREAMS: "1"
  VLLM_USE_V1: "1"
  NCCL_DEBUG: "INFO"
  HYDRA_FULL_ERROR: "1" 
  NCCL_NVLS_ENABLE: "0"
